name: Canary Release
on:
  schedule:
    # At minute 0 past every 2nd hour on every day-of-week from Monday through Friday.
    # https://crontab.guru/#0_22_*_*_*
    - cron: '0 22 * * 1,2,3,4,5'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Unshallow
        run: git fetch

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Hook private repo
        run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move build artifacts
        run: |
          mkdir ~/artifacts
          mv $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz ~/artifacts/linux.tar.gz
          mv $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip ~/artifacts/darwin.zip

      - name: List Build Artifacts
        run: ls -l ~/artifacts

      - name: Save Linux Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-linux
          path: ~/artifacts/linux.tar.gz
          if-no-files-found: error

      - name: Save MacOS Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-darwin
          path: ~/artifacts/darwin.zip
          if-no-files-found: error

  acceptance_test:
    name: Acceptance tests
    needs: build
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Prepare for downloads
        id: prepare-for-downloads
        run: |
          mkdir ~/artifacts

      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v2
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        with:
          name: build-artifact-linux
          path: ~/artifacts

      - name: Download Darwin Build Artifacts
        uses: actions/download-artifact@v2
        if: ${{ matrix.platform == 'macos-latest' }}
        with:
          name: build-artifact-darwin
          path: ~/artifacts

      - name: Extract Darwin Artifacts and Install Binary
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          mkdir ~/build
          unzip ~/artifacts/darwin.zip -d ~/build

      - name: Extract Ubuntu Artifacts and Install Binary
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          mkdir ~/build
          tar -xf ~/artifacts/linux.tar.gz -C ~/build

      - name: Set PATH
        run: |
          echo "PATH=$PATH:$HOME/build:$GTIHUB_WORKSPACE/tests/acceptance/lib/bats/bin" >> $GITHUB_ENV

      - name: Install DB
        run: |
          steampipe service start
          steampipe plugin install chaos
          steampipe service stop --force

      - name: Run Test Suite
        timeout-minutes: 5
        run: |
          chmod +x $GITHUB_WORKSPACE/tests/acceptance/run.sh
          $GITHUB_WORKSPACE/tests/acceptance/run.sh
          steampipe service stop --force
        
  create_release:
    name: Release
    needs: acceptance_test
    runs-on: ubuntu-latest
    steps:
      - name: Getting Last Release
        id: last_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: turbot/steampipe
          excludes: prerelease, draft

      - name: Get next patch version
        id: next-semver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.last_release.outputs.release }}

      - name: Get current formatted date
        id: current-date
        run: |
          echo '::set-output name=formatted_date::$(date +%Y%m%d)'

      - name: Calculating Next version
        id: next_version
        run: |
          echo '::set-output name=canary_version::${{format('v{0}-canary.{1}', steps.next-semver.outputs.patch, steps.current-date.outputs.formatted_date)}}'

      - name: Full version string
        run: |
          echo ${{ steps.next_version.outputs.canary_version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Unshallow
        run: git fetch
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Hook private repo
        run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"

      - name: Installing yq
        uses: mikefarah/yq@v4.7.1

      - name: Setting up goreleaser to build with canary version string
        run: |
          cat $GITHUB_WORKSPACE/.goreleaser.yml | yq e '.builds.0.ldflags[0]="-s -w -X main.steampipeVersion=${{ steps.next_version.outputs.canary_version }}"' - > $GITHUB_WORKSPACE/tmp_releaser.yml
          mv $GITHUB_WORKSPACE/tmp_releaser.yml $GITHUB_WORKSPACE/.goreleaser.yml
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        run: |
          gh release create ${{ steps.next_version.outputs.canary_version }} $GITHUB_WORKSPACE/dist/steampipe_linux_amd64.tar.gz $GITHUB_WORKSPACE/dist/steampipe_darwin_amd64.zip $GITHUB_WORKSPACE/dist/checksums.txt --title ${{ steps.next_version.outputs.canary_version }} --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clean_up:
    # let's clean up the artifacts.
    # incase this step isn't reached,
    # artifacts automatically expire after 90 days anyway
    # refer:
    #   https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-and-deleting-artifacts-after-a-workflow-run-is-complete
    name: Clean Up Artifacts
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Clean up Windows Build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-artifact-windows
          failOnError: false

      - name: Clean up Linux Build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-artifact-linux
          failOnError: false

      - name: Clean up Darwin Build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-artifact-darwin
          failOnError: false

      - name: Clean up Test Suite
        uses: geekyeggo/delete-artifact@v1
        with:
          name: test-artifact
          failOnError: false